---

- name: Handle errors
  hosts: webserver,dbserver
  become: true

  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Check local date
      ansible.builtin.command: date
      register: command_result
      changed_when: false

    - name: Display local date
      ansible.builtin.debug:
        msg: today is {{ command_result.stdout }}

    - name: Attempt to set up webser
      block:
        - name: Install {{ web_package }} package
          ansible.builtin.dnf:
            name: "{{ web_package }}"
            state: present
          failed_when: web_package != "httpd"

      rescue:
        - name: Install {{ db_package }} package
          ansible.builtin.dnf:
            name: "{{ db_package }}"
            state: present

      always:
        - name: Start {{ db_service }} service
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: started
            enabled: true
