---

- name: Install and manage services
  hosts: webserver
  become: true

  tasks:
    - name: Ensure latest version of packages are installed
      ansible.builtin.dnf:
        name: 
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
        state: latest

    - name: Ensure httpd config file is copied to the appropriate location
      ansible.builtin.copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_dest }}"
        owner: root
        group: root
        mode: 0644

    - name: Ensure directory for authentication files is created
      ansible.builtin.file:
        path: "{{ secrets_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: 0500

    - name: Ensure authentication files are copied to the appropriate location
      ansible.builtin.copy:
        src: "{{ secrets_src }}"
        dest: "{{ secrets_dest }}"
        owner: apache
        group: apache
        mode: 0400

    - name: Ensure access files exit
      ansible.builtin.copy:
        src: "{{ htaccess_src }}"
        dest: "{{ web_root }}/.htaccess"
        owner: apache
        group: apache
        mode: 0400

    - name: Ensure web content are created
      ansible.builtin.copy:
        content: >
          {{ ansible_facts.fqdn }}
          ({{ ansible_facts.default_ipv4.address }})
          has been customized by Ansible. 
        dest: "{{ web_root }}/index.html"

    - name: Ensure firewalld is started
      ansible.builtin.service:
        name: "{{ firewall_svc }}"
        state: started
        enabled: true

    - name: Ensure access to https is enabled
      ansible.posix.firewalld:
        service: https
        state: enabled
        immediate: true
        permanent: true

    - name: Ensure the web service is started
      ansible.builtin.service:
        name: "{{ web_svc }}"
        state: started
        enabled: true

- name: Web server authentication
  hosts: localhost
  become: false

  vars:
    web_user: cloud_user

  vars_files:
    - vars/secret.yml

  tasks:
    - name: Ensure web server authentication
      ansible.builtin.uri:
        url: https://172.31.106.57
        validate_certs: false
        force_basic_auth: true
        user: "{{ web_user }}"
        password: "{{ web_pass }}"
        return_content: true
        status_code: 200
      register: auth_test

    - name: Print content from web server
      ansible.builtin.debug:
        var: auth_test.content
         




        


     
      
          

